# This is a basic workflow to help you get started with Actions

name: Deploy geek-contract app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
    
    environment: github-pages

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '19.x'

      - name: Create env file
        run: |
          touch .env
          echo REACT_APP_tronweb_fullHost=${{ secrets.FULL_HOST }} >> .env
          echo REACT_APP_tronweb_apikey=${{ secrets.API_KEY }} >> .env
          echo REACT_APP_verifier=${{ secrets.VERIFIER }} >> .env
          echo REACT_APP_test_case_abi_temp="[{\"components\":[{\"name\":\"input\",\"type\":\"inputType\"},{\"name\":\"output\",\"type\":\"outputType\"}],\"name\":\"\",\"type\":\"tuple\"}]" >> .env

      - name: npm install, build
        run: |
          npm install
          npm run build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: build